project:
  type: website
  output-dir: docs

website:
  title: "Data In The Wild"
  favicon: images/bdsc-logo-hex.png
  
  navbar:
    logo: images/bdsc-logo-hex.png
    left:
      - href: index.qmd
        text: Home
      - href: course_materials.qmd
        text: Course Materials
    right: 
      - href: about.qmd
        text: Resources
        
  sidebar: 
      style: docked
      contents: 
        - section: "Introduction"
          contents: 
            - course_materials.qmd
            - structure.qmd
        - section: "Modules"
          contents: 
            - module1.qmd
            - module2.qmd
            - module3.qmd
            - module4.qmd
        
  page-footer: 
    background: $dark-blue
    foreground: $blanched-almond
    left: "Copyright 2024, University of Arizona | Last modified: 5 April 2024"
    right: 
      - href: https://quarto.org/
        text: "Made with Quarto"
      - href: https://github.com/BiodiversityDataScienceCorp/DataInTheWild_Website
        icon: github

format:
  html:
    theme:
      - styles.scss
    mainfont: "Vollkorn"
    page-layout: full

editor: visual

