---
title: "Course Structure"
format:
  html:
    toc: false
---

## The Full Course Cheese Board

This page serves as an inventory of the material associated with each subsection of this site. These are also available in the Data in the Wild Github repository, which can be accessed here: \[insert link of canonical version\].

***Note*****:** The instructor versions of lessons are also available as PDFs, and they can be downloaded from the righthand table of contents within the respective module subsection (e.g. Click on 1.1: Introduction to RStudio in the left sidebar \> navigate your attention to the table of contents on the right side of the screen \> the link to the PDF should be the last option).

+--------+---------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------+---+---+
| Module | Title                                                         | Lecture / Code-along (.Rmd)                                                                                                                                        | Data sets (.csv)                    | Discussions (.txt)                                                                                                                              | Assignments (.Rmd)                                                                                                                                       |   |   |
+:======:+:=============================================================:+:==================================================================================================================================================================:+:===================================:+:===============================================================================================================================================:+:========================================================================================================================================================:+===+===+
| 1.1    | Introduction to RStudio                                       | [Student](https://raw.githubusercontent.com/BiodiversityDataScienceCorp/DataInTheWild_UA/main/modules/module_1/lessons/Module1_1_IntrotoRStudio.Rmd)               | Figure how to download all in a zip | [Discussion 1](https://raw.githubusercontent.com/BiodiversityDataScienceCorp/DataInTheWild_UA/main/modules/module_1/discussions/discussion_1_1) | Assignment 1                                                                                                                                             |   |   |
|        |                                                               |                                                                                                                                                                    |                                     |                                                                                                                                                 |                                                                                                                                                          |   |   |
|        |                                                               | [Instructor](https://raw.githubusercontent.com/BiodiversityDataScienceCorp/DataInTheWild_UA/main/modules/module_1/lessons/Module1_1_IntrotoRStudio_Instructor.Rmd) |                                     | [Discussion 2](https://raw.githubusercontent.com/BiodiversityDataScienceCorp/DataInTheWild_UA/main/modules/module_1/discussions/discussion_1_2) | [Assignment 2](https://raw.githubusercontent.com/BiodiversityDataScienceCorp/DataInTheWild_UA/main/modules/module_1/assignments/Module1_Assignment2.Rmd) |   |   |
|        |                                                               |                                                                                                                                                                    |                                     |                                                                                                                                                 |                                                                                                                                                          |   |   |
|        |                                                               |                                                                                                                                                                    |                                     |                                                                                                                                                 | [Assignment 3](https://raw.githubusercontent.com/BiodiversityDataScienceCorp/DataInTheWild_UA/main/modules/module_1/assignments/Module1_Assignment3.Rmd) |   |   |
+--------+---------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------+---+---+
| 1.2    | Introduction to Coding                                        | Student                                                                                                                                                            |                                     | Discussion 1                                                                                                                                    |                                                                                                                                                          |   |   |
|        |                                                               |                                                                                                                                                                    |                                     |                                                                                                                                                 |                                                                                                                                                          |   |   |
|        |                                                               | Instructor                                                                                                                                                         |                                     | Discussion 2                                                                                                                                    |                                                                                                                                                          |   |   |
+--------+---------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------+---+---+
| 1.3    | 2-dimensional Data and the `tidyverse`                        | Student                                                                                                                                                            |                                     | Discussion 1                                                                                                                                    |                                                                                                                                                          |   |   |
|        |                                                               |                                                                                                                                                                    |                                     |                                                                                                                                                 |                                                                                                                                                          |   |   |
|        |                                                               | Instructor                                                                                                                                                         |                                     | Discussion 2                                                                                                                                    |                                                                                                                                                          |   |   |
+--------+---------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------+---+---+
| 2.1    | Introduction to Descriptive Statistics and Data Visualization | Student                                                                                                                                                            |                                     | Discussion 1                                                                                                                                    |                                                                                                                                                          |   |   |
|        |                                                               |                                                                                                                                                                    |                                     |                                                                                                                                                 |                                                                                                                                                          |   |   |
|        |                                                               | Instructor                                                                                                                                                         |                                     | Discussion 2                                                                                                                                    |                                                                                                                                                          |   |   |
+--------+---------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------+---+---+
| 2.2    | Writing Functions                                             | Student                                                                                                                                                            |                                     | Discussion 1                                                                                                                                    |                                                                                                                                                          |   |   |
|        |                                                               |                                                                                                                                                                    |                                     |                                                                                                                                                 |                                                                                                                                                          |   |   |
|        |                                                               | Instructor                                                                                                                                                         |                                     | Discussion 2                                                                                                                                    |                                                                                                                                                          |   |   |
+--------+---------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------+---+---+
| 2.3    | Plotting with `ggplot2`                                       | Student                                                                                                                                                            |                                     | Discussion 1                                                                                                                                    |                                                                                                                                                          |   |   |
|        |                                                               |                                                                                                                                                                    |                                     |                                                                                                                                                 |                                                                                                                                                          |   |   |
|        |                                                               | Instructor                                                                                                                                                         |                                     | Discussion 2                                                                                                                                    |                                                                                                                                                          |   |   |
+--------+---------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------+---+---+
| 2.4    | A Visualization Primer                                        | Student                                                                                                                                                            |                                     | Discussion 1                                                                                                                                    |                                                                                                                                                          |   |   |
|        |                                                               |                                                                                                                                                                    |                                     |                                                                                                                                                 |                                                                                                                                                          |   |   |
|        |                                                               | Instructor                                                                                                                                                         |                                     | Discussion 2                                                                                                                                    |                                                                                                                                                          |   |   |
+--------+---------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------+---+---+
| 2.5    | Sick Fish                                                     | Student                                                                                                                                                            |                                     | Discussion 1                                                                                                                                    |                                                                                                                                                          |   |   |
|        |                                                               |                                                                                                                                                                    |                                     |                                                                                                                                                 |                                                                                                                                                          |   |   |
|        |                                                               | Instructor                                                                                                                                                         |                                     | Discussion 2                                                                                                                                    |                                                                                                                                                          |   |   |
+--------+---------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------+---+---+
| 2.6    | Exploring `geom` Functions                                    | Student                                                                                                                                                            |                                     | Discussion 1                                                                                                                                    |                                                                                                                                                          |   |   |
|        |                                                               |                                                                                                                                                                    |                                     |                                                                                                                                                 |                                                                                                                                                          |   |   |
|        |                                                               | Instructor                                                                                                                                                         |                                     | Discussion 2                                                                                                                                    |                                                                                                                                                          |   |   |
+--------+---------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------+---+---+
| 2.7    | Wrap-Up                                                       | Student                                                                                                                                                            |                                     | Discussion 1                                                                                                                                    |                                                                                                                                                          |   |   |
|        |                                                               |                                                                                                                                                                    |                                     |                                                                                                                                                 |                                                                                                                                                          |   |   |
|        |                                                               | Instructor                                                                                                                                                         |                                     | Discussion 2                                                                                                                                    |                                                                                                                                                          |   |   |
+--------+---------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------+---+---+
| 3.1    | Leopard Seals                                                 | Student                                                                                                                                                            |                                     | Discussion 1                                                                                                                                    |                                                                                                                                                          |   |   |
|        |                                                               |                                                                                                                                                                    |                                     |                                                                                                                                                 |                                                                                                                                                          |   |   |
|        |                                                               | Instructor                                                                                                                                                         |                                     | Discussion 2                                                                                                                                    |                                                                                                                                                          |   |   |
+--------+---------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------+---+---+
| 3.2    | T-Tests                                                       | Student                                                                                                                                                            |                                     | Discussion 1                                                                                                                                    |                                                                                                                                                          |   |   |
|        |                                                               |                                                                                                                                                                    |                                     |                                                                                                                                                 |                                                                                                                                                          |   |   |
|        |                                                               | Instructor                                                                                                                                                         |                                     | Discussion 2                                                                                                                                    |                                                                                                                                                          |   |   |
+--------+---------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------+---+---+
| 3.3    | Comparing (Multiple) Means                                    | Student                                                                                                                                                            |                                     | Discussion 1                                                                                                                                    |                                                                                                                                                          |   |   |
|        |                                                               |                                                                                                                                                                    |                                     |                                                                                                                                                 |                                                                                                                                                          |   |   |
|        |                                                               | Instructor                                                                                                                                                         |                                     | Discussion 2                                                                                                                                    |                                                                                                                                                          |   |   |
+--------+---------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------+---+---+
| 3.4    | Combining Data (Joins and Binds)                              | Student                                                                                                                                                            |                                     | Discussion 1                                                                                                                                    |                                                                                                                                                          |   |   |
|        |                                                               |                                                                                                                                                                    |                                     |                                                                                                                                                 |                                                                                                                                                          |   |   |
|        |                                                               | Instructor                                                                                                                                                         |                                     | Discussion 2                                                                                                                                    |                                                                                                                                                          |   |   |
+--------+---------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------+---+---+
| 3.5    | K-Nearest Neighbor                                            | Student                                                                                                                                                            |                                     | Discussion 1                                                                                                                                    |                                                                                                                                                          |   |   |
|        |                                                               |                                                                                                                                                                    |                                     |                                                                                                                                                 |                                                                                                                                                          |   |   |
|        |                                                               | Instructor                                                                                                                                                         |                                     | Discussion 2                                                                                                                                    |                                                                                                                                                          |   |   |
+--------+---------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------+---+---+
| 4.1    | Roads and Regressions                                         | Student                                                                                                                                                            |                                     | Discussion 1                                                                                                                                    |                                                                                                                                                          |   |   |
|        |                                                               |                                                                                                                                                                    |                                     |                                                                                                                                                 |                                                                                                                                                          |   |   |
|        |                                                               | Instructor                                                                                                                                                         |                                     | Discussion 2                                                                                                                                    |                                                                                                                                                          |   |   |
+--------+---------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------+---+---+
| 4.2    | Multiple Regression                                           | Student                                                                                                                                                            |                                     | Discussion 1                                                                                                                                    |                                                                                                                                                          |   |   |
|        |                                                               |                                                                                                                                                                    |                                     |                                                                                                                                                 |                                                                                                                                                          |   |   |
|        |                                                               | Instructor                                                                                                                                                         |                                     | Discussion 2                                                                                                                                    |                                                                                                                                                          |   |   |
+--------+---------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------+---+---+
| 4.3    | Using Functions to Automate Tasks                             | Student                                                                                                                                                            |                                     | Discussion 1                                                                                                                                    |                                                                                                                                                          |   |   |
|        |                                                               |                                                                                                                                                                    |                                     |                                                                                                                                                 |                                                                                                                                                          |   |   |
|        |                                                               | Instructor                                                                                                                                                         |                                     | Discussion 2                                                                                                                                    |                                                                                                                                                          |   |   |
+--------+---------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------+---+---+
