project:
  type: website

website:
  title: "Data In The Wild"
  favicon: images/bdsc-logo-hex.png
  navbar:
    logo: images/bdsc-logo-hex.png
    left:
      - href: index.qmd
        text: Home
      - href: structure.qmd
        text: Structure
      - href: modules.qmd
        text: Modules
    right: 
      - href: about.qmd
        text: Resources
  page-footer: 
    background: $dark-blue
    foreground: $blanched-almond
    left: "Copyright 2024, University of Arizona | Last modified: 25 January 2024"
    right: 
      - href: https://quarto.org/
        text: "Made with Quarto"
      - href: https://github.com/BiodiversityDataScienceCorp/DataInTheWild_Website
        icon: github

format:
  html:
    theme:
      - styles.scss
    mainfont: "Vollkorn"
    page-layout: full

editor: visual

