<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Data In The Wild - 4.1: Roads and Regressions</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<link href="../../images/bdsc-logo-hex.png" rel="icon" type="image/png">
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar docked nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a href="../../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../../images/bdsc-logo-hex.png" alt="" class="navbar-logo">
    </a>
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Data In The Wild</span>
    </a>
  </div>
        <div class="quarto-navbar-tools ms-auto">
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../modules/module_4/module4_1.html">Module 4</a></li><li class="breadcrumb-item"><a href="../../modules/module_4/module4_1.html">4.1: Roads and Regressions</a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-center sidebar-header">
      <a href="../../index.html" class="sidebar-logo-link">
      <img src="../../images/bdsc-logo-hex.png" alt="" class="sidebar-logo py-0 d-lg-inline d-none">
      </a>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="false">
 <span class="menu-text">Introduction</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Data In The Wild</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../structure.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Course Structure</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="false">
 <span class="menu-text">Module 1</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../modules/module_1/module1_1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">1.1: Introduction to RStudio</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../modules/module_1/module1_2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">1.2: Introduction to Coding</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../modules/module_1/module1_3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">1.3: 2-Dimensional Data and the <code>tidyverse</code></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="false">
 <span class="menu-text">Module 2</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../modules/module_2/module2_1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2.1: Introduction to Descriptive Statistics and Data Visualization</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../modules/module_2/module2_2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2.2: Writing Functions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../modules/module_2/module2_3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2.3: Plotting with <code>ggplot2</code></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../modules/module_2/module2_4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2.4: A Visualization Primer</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../modules/module_2/module2_5.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2.5: Sick Fish</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../modules/module_2/module2_6.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2.6: Exploring <code>geom</code> Functions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../modules/module_2/module2_7.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2.7: Wrap-Up</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="false">
 <span class="menu-text">Module 3</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../modules/module_3/module3_1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">3.1: Leopard Seals</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../modules/module_3/module3_2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">3.2: T-Tests</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../modules/module_3/module3_3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">3.3: Comparing (Multiple) Means</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../modules/module_3/module3_4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">3.4: Combining Data (Joins and Binds)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../modules/module_3/module3_5.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">3.5: K-Nearest Neighbor</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true">
 <span class="menu-text">Module 4</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../modules/module_4/module4_1.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">4.1: Roads and Regressions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../modules/module_4/module4_2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">4.2: Multiple Regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../modules/module_4/module4_3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Using Functions to Automate Tasks</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="false">
 <span class="menu-text">Resources</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../about.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">About Us</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content column-page-right" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">4.1: Roads and Regressions</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="the-scenario" class="level2">
<h2 class="anchored" data-anchor-id="the-scenario">The Scenario</h2>
<p>Last module, we tried to figure out which bays we should prioritize for fishing based on the following data sets:</p>
<ul>
<li>Radio collar data</li>
<li>Fish catch data</li>
<li>Leopard seal abundance data</li>
</ul>
<p>Based on our results from Assignment 2, it looks like Sulzberger Bay and Hope Bay are our best bets. Now, we need to make these bays accessible over land to transport the fish we’ve caught to our home base.</p>
<p><strong>We want to build a road while minimizing our impact on the delicate antarctic ecosystem.</strong></p>
<p>Our first order of business is to make sure that we avoid areas with that are well-suited for <a href="https://oceanwide-expeditions.com/blog/the-plants-of-antarctic">Antarctica hair grass</a> (<em>Deschamsia antarctica</em>), one of only two flowering species of plants on the continent.</p>
<p><img src="assets/hairgrass_indiv.jpeg" class="img-fluid"></p>
<p>We want to know what environmental conditions are associated with hair grass. This way, we can avoid areas where these conditions are met and not destroy precious habitat for the hair grass.</p>
<p>It would take far too long to survey every bit of land between our base and our fishing spots, so we are going to build a <strong>model</strong> based on some samples of where hair grass is found to help us predict where else it might be.</p>
<section id="what-is-a-model" class="level3">
<h3 class="anchored" data-anchor-id="what-is-a-model">What is a model?</h3>
<p>A model is a way for us to take complex systems and break them down into small, more understandable bits. We can use models to help us understand the relationship between different variables. We can then use those model to make predictions based on those relationships.</p>
</section>
</section>
<section id="data" class="level2">
<h2 class="anchored" data-anchor-id="data">Data</h2>
<p><img src="assets/hairgrass_landscape.jpeg" class="img-fluid"></p>
<p>Knowing that we would soon be building roads, we asked our botanists to collect data for us on key components of the hairgrass’ environment. Since it would take too long to sample everywhere hairgrass grows, they collected data from a sample of the hairgrass population.</p>
<p>Our botanists collected data for the following variables:</p>
<ul>
<li><strong><em>soil pH</em>:</strong> most plants prefer mildly acidic to neutral environments</li>
<li><strong><em>nitrogen (N) content</em>:</strong> as percentage per 100 mL soil sample; important for plant growth and tissue building</li>
<li><strong><em>phosphorous (P) content</em>:</strong> as percentage per 100 mL soil sample; important for plant growth and tissue building</li>
<li><strong><em>percent rock</em>:</strong> how rocky the location is; rocks in soil impact water drainage and temperature</li>
<li><strong><em>max windspeed (knots per hour)</em>:</strong> extreme wind can pose a challenge to plants of all types</li>
<li><strong><em>average summer temperature (C)</em>:</strong> temperature in the growing season</li>
<li><strong><em>penguin density</em>:</strong> the number of penguins per 5 m^2 within 100 m of the sample quadrant for hair grass; penguin poop increases nitrogen content in the system</li>
<li><strong><em>hairgrass density</em>:</strong> number of individual clumps (tussocks) of hairgrass per 1 m^2</li>
</ul>
<p>This data is based on this article: <a href="https://doi.org/10.1016/j.polar.2007.10.002">Parnikoza, et al.&nbsp;2007</a></p>
</section>
<section id="summarize-and-visualize" class="level2">
<h2 class="anchored" data-anchor-id="summarize-and-visualize">Summarize and Visualize</h2>
<p>As we see above, there are many environmental conditions that may be associated with hair grass density.</p>
<p>For this lesson, we are going to focus on two: <em>nitrogen (N) content</em> and <em>soil pH</em>.</p>
<section id="set-up" class="level3">
<h3 class="anchored" data-anchor-id="set-up">Set-Up</h3>
<p>As usual, we start with loading our packages and our data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load library</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Load data</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>hairgrass <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/hairgrass_data.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let’s take a look at the data in the data set. What does each row represent?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># View first few rows</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(hairgrass)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 10
  location_ID soil_pH p_content percent_soil_rock max_windspeed_knots
        &lt;dbl&gt;   &lt;dbl&gt;     &lt;dbl&gt;             &lt;dbl&gt;               &lt;dbl&gt;
1           1    4.9     5.49                44.5                14.9
2           2    6.94    8.53                50.5                11.0
3           3    4.36    0.0801              88.5                26.5
4           4    5.41    1.98                61                  23.6
5           5    5.32    6.6                 67.1                27.4
6           6    6.49    4.09                42.8                22.6
# ℹ 5 more variables: avg_uv_index &lt;dbl&gt;, avg_summer_temp &lt;dbl&gt;,
#   n_content &lt;dbl&gt;, hairgrass_density_m2 &lt;dbl&gt;, penguin_density_5m2 &lt;dbl&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># View last few rows</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">tail</span>(hairgrass)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 10
  location_ID soil_pH p_content percent_soil_rock max_windspeed_knots
        &lt;dbl&gt;   &lt;dbl&gt;     &lt;dbl&gt;             &lt;dbl&gt;               &lt;dbl&gt;
1         475    4.57     7.96               96.2               25.5 
2         476    6.1      0.448              94.5                5.00
3         477    4.72     4.86               70.3               12.3 
4         478    6.41     3.8                86.9                4.86
5         479    6.02     4.62               12                  7.23
6         480    3.64     2.32               94.9                3.94
# ℹ 5 more variables: avg_uv_index &lt;dbl&gt;, avg_summer_temp &lt;dbl&gt;,
#   n_content &lt;dbl&gt;, hairgrass_density_m2 &lt;dbl&gt;, penguin_density_5m2 &lt;dbl&gt;</code></pre>
</div>
</div>
</section>
<section id="nitrogen-content" class="level3">
<h3 class="anchored" data-anchor-id="nitrogen-content">Nitrogen Content</h3>
<p>Let’s start by investigating any relationship between hair grass density and nitrogen content.</p>
<p>First, we should spend a little time thinking about our variables. Spend a few minutes in small groups discussing the answer to the questions below.</p>
<ul>
<li>Which columns are we interested in right now? <strong>N_content, hairgrass_density</strong></li>
<li>Which one is the independent variable and which is the dependent variable?
<ul>
<li>independent: <strong>N_content</strong></li>
<li>dependent: <strong>hairgrass_density_m2</strong></li>
</ul></li>
<li>Are the variables categorical or continuous? <strong>Both are continuous</strong></li>
<li>Which type of data visualization should we use? <strong>Scatterplot</strong></li>
</ul>
<p>Next, calculate the mean (<code>mean()</code>) and standard deviation (<code>sd()</code>) for the nitrogen content.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Mean and standard deviation of nitrogen content</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>hairgrass <span class="sc">%&gt;%</span> </span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">mean_N =</span> <span class="fu">mean</span>(n_content),</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">sd_N =</span> <span class="fu">sd</span>(n_content))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 2
  mean_N  sd_N
   &lt;dbl&gt; &lt;dbl&gt;
1   9.93  1.02</code></pre>
</div>
</div>
<p>Now that we have summarized the data, let’s take a look at the data visually.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Scatterplot</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(hairgrass, <span class="fu">aes</span>(n_content, hairgrass_density_m2)) <span class="sc">+</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"N Content"</span>,</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Hairgrass Density (per m^2)"</span>) <span class="sc">+</span></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="module4_1_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Do you see a pattern? What type of relationship do you see?</p>
<p>How do we analyze this type of relationship statistically?</p>
</section>
</section>
<section id="statistical-analysis" class="level2">
<h2 class="anchored" data-anchor-id="statistical-analysis">Statistical Analysis</h2>
<p>We are going to use two (related) statistical methods to understand the relationship between two continuous (numeric) variables:</p>
<ul>
<li>Correlation coefficient (<span class="math inline">\(r\)</span>) and R-squared (<span class="math inline">\(R^2\)</span>)</li>
<li>Linear regression</li>
</ul>
<section id="line-of-best-fit" class="level3">
<h3 class="anchored" data-anchor-id="line-of-best-fit">Line of Best Fit</h3>
<p>To understand correlation, R-squared, and linear regression, we first need to talk about something we call the <em>line of best fit</em>.</p>
<p>The line of best fit aims to minimize the distance between each observation (points) and the line. The distances between each observation and any line are called <em>residuals</em> (the dotted gray lines). The line of best fit is the line that has the smallest <em>residuals</em>.</p>
<p><img src="assets/lines.png" class="img-fluid"> <img src="assets/residuals.jpg" class="img-fluid"></p>
<p>We can add a line of best fit to a ggplot by using the <code>geom_smooth()</code> function. We need to specify that the method we want should produce a straight line (“linear model”).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Scatterplot</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(hairgrass, <span class="fu">aes</span>(n_content, hairgrass_density_m2)) <span class="sc">+</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>) <span class="sc">+</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"N Content"</span>,</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Hairgrass Density (per m^2)"</span>) <span class="sc">+</span></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="module4_1_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="correlation-coefficient" class="level3">
<h3 class="anchored" data-anchor-id="correlation-coefficient">Correlation Coefficient</h3>
<p>The correlation coefficient, <code>r</code>, is a measurement of the strength of the relationship between two continuous variables.</p>
<p>The correlation coefficient is a number between -1 and 1 that looks at the relationship between two numeric variables. If the value is negative, there is a negative relationship between the two variable; if the value is positive, there is a positive relationship.</p>
<p>If all the points fall exactly on the line of best fit, r = 1 or -1. If there is no relationship between the variables, <code>r</code> is 0 (or something very close to it).</p>
<p><img src="assets/coefficient_correlation.jpg" class="img-fluid"></p>
<p>The greater the magnitude (size) of the correlation coefficient, the stronger the relationship between the two variables.</p>
<p><img src="assets/correlation.jpg" class="img-fluid"></p>
<p>It is also important to recognize that the correlation coefficient has nothing to do with the slope of the line (we use linear regression to assess that!).</p>
<p><img src="assets/steepness.jpeg" class="img-fluid"></p>
<p>Based on the hairgrass plot we did above, do you expect the correlation coefficient to be positive or negative? For this class, we’ll say that any <code>r</code> value with 0.1 of 0 means there is no relationship.</p>
<p>To calculate the correlation coefficient, we need to go back to base R and indicate which columns we are referencing with the <code>$</code> operator. We use the <code>cor()</code> function.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Find the correlation coefficient</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>r <span class="ot">&lt;-</span> <span class="fu">cor</span>(<span class="at">x =</span> hairgrass<span class="sc">$</span>n_content, <span class="at">y =</span> hairgrass<span class="sc">$</span>hairgrass_density_m2)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="co"># View result</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>r</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.6556456</code></pre>
</div>
</div>
</section>
<section id="r-squared-r2" class="level3">
<h3 class="anchored" data-anchor-id="r-squared-r2">R-squared (<span class="math inline">\(R^2\)</span>)</h3>
<p>The R-squared (<span class="math inline">\(R^2\)</span>) value is a representation of how much variation is explained by the line of best fit.</p>
<p>When we have a dependent variable and an independent variable, the R-squared value tells us how much of the variation in the <em>dependent</em> variable is explained by the <em>independent</em> variable.</p>
<p>Sometimes we don’t have obvious dependent and independent variables, but we can still use similar language (<span class="math inline">\(R^2\)</span> tells us how much of the variation in the data is explained).</p>
<p>To calculate R-squared, we square the correlation coefficient value we calculated above. It is always positive because we are squaring it <code>r</code> value; that means that R-squared values range from 0 to 1. The closer to 1, the more variation is explained.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># What is r^2?</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>r<span class="sc">^</span><span class="dv">2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.4298711</code></pre>
</div>
</div>
<p>How would we interpret this <code>r^2</code> value?</p>
</section>
<section id="linear-regression-analysis" class="level3">
<h3 class="anchored" data-anchor-id="linear-regression-analysis">Linear Regression Analysis</h3>
<p>A regression analysis approximates the relationship between a dependent variable and one or more independent variables. It evaluates the strength of that relationship, ultimately giving us a p-value.</p>
<p>Since we are using linear regressions in this course, the regression model will take the form of a line: <code>y = mx + b</code></p>
<ul>
<li><code>y</code> = dependent variable (y-axis)</li>
<li><code>x</code> = independent variable (x-axis)</li>
<li><code>m</code> = slope of the line is the slope</li>
<li><code>b</code> = y-intercept</li>
</ul>
<p>Using our variables, what would our linear regression model look like (we don’t know <code>m</code> or <code>b</code> yet…)?</p>
</section>
<section id="hypothesis-testing" class="level3">
<h3 class="anchored" data-anchor-id="hypothesis-testing">Hypothesis Testing</h3>
<p>What is the null hypothesis? What is the alternative hypothesis?</p>
<p><strong>Null Hypothesis</strong> (<span class="math inline">\(H_{0}\)</span>): There is <em>no</em> relationship between hair grass density and nitrogen content.</p>
<p><strong>Alternative Hypothesis</strong> (<span class="math inline">\(H_{A}\)</span>): There <em>is</em> a relationship between hair grass density and nitrogen content.</p>
<p>What do you think this means for the slopes?</p>
</section>
<section id="regression-analysis" class="level3">
<h3 class="anchored" data-anchor-id="regression-analysis">Regression Analysis</h3>
<p>Thankfully, R can calculate the slope (<code>m</code>) and y-intercept (<code>b</code>) of the line of best fit for us.</p>
<p>Let’s find the equation for our line of best fit, our test statistic, and our p-value. To do this, we use a function called <code>lm()</code>: this stands for “linear model.”</p>
<p>Like with ANOVA, we will then want to use the <code>summary()</code> function to get out the values we need.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Linear model of hairgrass density v. nitrogen content</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>nitrogen <span class="ot">&lt;-</span> <span class="fu">lm</span>(hairgrass_density_m2 <span class="sc">~</span> n_content, hairgrass)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Summary of results</span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(nitrogen)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = hairgrass_density_m2 ~ n_content, data = hairgrass)

Residuals:
     Min       1Q   Median       3Q      Max 
-2.50324 -0.53853  0.01917  0.49500  2.25562 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  1.38516    0.34636   3.999 7.36e-05 ***
n_content    0.65886    0.03471  18.984  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.7765 on 478 degrees of freedom
Multiple R-squared:  0.4299,    Adjusted R-squared:  0.4287 
F-statistic: 360.4 on 1 and 478 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>As with our other statistical tests — t-tests and ANOVAs — the results give us some important values:</p>
<ul>
<li><code>b</code> (y-intercept): part of our line of best fit equation
<ul>
<li>The “intercept estimate”, in this case 1.385, is our y-intercept in our line of best fit</li>
</ul></li>
<li><code>m</code> (slope): also part of our line of best fit equation
<ul>
<li>This is the estimate for our independent variable (N_content in this case)</li>
<li>In this model, m = 0.659</li>
</ul></li>
<li><em>F-statistic</em>: this is our test statistic</li>
<li><em>p-value</em>: calculated from our regression model, used to determine significance (0.05 cut-off, as usual)
<ul>
<li>There are multiple p-values here. Focus either on the p-value for the independent variable (N_content) or the overall p-value displayed in the last line of the results summary (p &lt; 2.2e-16)</li>
</ul></li>
<li><em>R-squared</em>: this is our R-squared value that we calculated earlier
<ul>
<li>You can report either the “multiple” or the “adjusted”</li>
<li>The “multiple” will typically match the one we calculate with code</li>
</ul></li>
</ul>
<p>This means our equation for the line of best fit is: y = 0.659x + 1.385 and there is a statistically significant relationship between nitrogen content and hairgrass density.</p>
</section>
</section>
<section id="soil-ph" class="level2">
<h2 class="anchored" data-anchor-id="soil-ph">Soil pH</h2>
<p>Let’s do the same series of steps to determine how soil pH impacts hair grass densities. Work on this in your small groups, and we will go over it in about 10 minutes.</p>
<p>Start with summarizing the data: mean and standard deviation.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Mean and standard deviation of soil pH</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>hairgrass <span class="sc">%&gt;%</span> </span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">mean_pH =</span> <span class="fu">mean</span>(soil_pH),</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">sd_pH =</span> <span class="fu">sd</span>(soil_pH))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 2
  mean_pH sd_pH
    &lt;dbl&gt; &lt;dbl&gt;
1    5.54  1.30</code></pre>
</div>
</div>
<p>Visualize the data. Remember to add in the line of best fit using <code>ggplot2</code>. Also add labels and a theme for practice.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Scatterplot</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(hairgrass, <span class="fu">aes</span>(soil_pH, hairgrass_density_m2)) <span class="sc">+</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>) <span class="sc">+</span></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Soil pH"</span>,</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Hairgrass Density per m^2"</span>) <span class="sc">+</span> </span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="module4_1_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Calculate the correlation coefficient (<code>r</code>)? What does this tell us?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Correlation coefficient</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>r <span class="ot">&lt;-</span> <span class="fu">cor</span>(<span class="at">x =</span> hairgrass<span class="sc">$</span>soil_pH, <span class="at">y =</span> hairgrass<span class="sc">$</span>hairgrass_density_m2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>How much variation does soil pH explain in the hair grass density data?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># What is r^2?</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>r<span class="sc">^</span><span class="dv">2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.003962606</code></pre>
</div>
</div>
<p>Write out the model for our question about soil pH (without values)?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># hairgrass density  = m(soil_pH) + b</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Run the regression model and write out the equation for the line of best fit.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Linear model of hairgrass density v. soil pH</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>soil_pH <span class="ot">&lt;-</span> <span class="fu">lm</span>(hairgrass_density_m2 <span class="sc">~</span> soil_pH, <span class="at">data =</span> hairgrass)</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(soil_pH)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = hairgrass_density_m2 ~ soil_pH, data = hairgrass)

Residuals:
     Min       1Q   Median       3Q      Max 
-2.95914 -0.66321  0.02364  0.65938  2.64477 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  7.65039    0.20531  37.263   &lt;2e-16 ***
soil_pH      0.04972    0.03605   1.379    0.169    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.026 on 478 degrees of freedom
Multiple R-squared:  0.003963,  Adjusted R-squared:  0.001879 
F-statistic: 1.902 on 1 and 478 DF,  p-value: 0.1685</code></pre>
</div>
</div>
<p>Equation for line of best fit: y = 0.005x + 7.65</p>
<p>Interpret the results of the regression (our p-value cutoff is still = 0.05). What do we conclude about the relationship between soil pH and hair grass density? Why?</p>
<p>Because p &gt; 0.05 for the regression model, we fail to reject the null hypothesis and conclude that there is no relationship between soil pH and hairgrass density.</p>
</section>
<section id="data-driven-decision-making" class="level2">
<h2 class="anchored" data-anchor-id="data-driven-decision-making">Data-driven Decision Making</h2>
<p>The reason we are using regression analysis is to inform where we should (or should not) build our road so we don’t harm the sensitive hair grass or take away their prime habitat.</p>
<p>What do results above for nitrogen content and soil pH mean for the road we are building?</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">Copyright 2024, University of Arizona | Last modified: 7 June 2024</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item">
    <a class="nav-link" href="https://quarto.org/">Made with Quarto</a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/BiodiversityDataScienceCorp/DataInTheWild_Website">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>



</body></html>